var R=require("../chunks/ssr/[turbopack]_runtime.js")("server/app/page.js")
R.c("server/chunks/ssr/[root-of-the-server]__d1f9773d._.js")
R.c("server/chunks/ssr/_6139f1ce._.js")
R.c("server/chunks/ssr/_27f38564._.js")
R.c("server/chunks/ssr/[root-of-the-server]__0937e251._.js")
R.c("server/chunks/ssr/node_modules_next_dist_241c23c8._.js")
R.c("server/chunks/ssr/node_modules_next_dist_compiled_bc6b8ddf._.js")
R.c("server/chunks/ssr/[root-of-the-server]__5d55e22f._.js")
R.c("server/chunks/ssr/node_modules_next_dist_25a30daf._.js")
R.c("server/chunks/ssr/app_b9b1292a._.js")
R.c("server/chunks/ssr/node_modules_next_dist_client_components_builtin_global-error_ece394eb.js")
R.c("server/chunks/ssr/[root-of-the-server]__65af543b._.js")
R.c("server/chunks/ssr/node_modules_next_dist_client_components_9774470f._.js")
R.c("server/chunks/ssr/node_modules_next_dist_client_components_builtin_forbidden_45780354.js")
R.c("server/chunks/ssr/node_modules_next_dist_client_components_builtin_unauthorized_15817684.js")
R.c("server/chunks/ssr/_next-internal_server_app_page_actions_39d4fc33.js")
R.m(43660)
module.exports=R.m(43660).exports
